spring:
  datasource:
    url: 'jdbc:h2:mem:demoCurrency'
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: password
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update  #自動更新db模式